language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run clear
  - npm run coverage
  - npm run build:publish

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
